- name: Email
  label: wevorence@gmail.com
  href: mailto:wevorence@gmail.com

- name: Github
  label: wasuken
  href: https://github.com/wasuken

- name: Blog
  label: 基本的に怠惰iary
  href: https://blog.londone.net

- name: Scrapbox
  label: 読書メモ置き場
  href: https://scrapbox.io/burden-reading/
